# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  mondongo:
    class: sfMondongoDatabase
    param:
      server:   mongodb://localhost:27017
      database: mondongo_database
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=sandbox
      username: root
      password: 
